title: About our plante
author: Biplob Sutradhar
email: biplobsd11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn amazing fact about our planet.

# social links
twitter_username: alpha4_d # DO NOT include the @ character, or else the build will fail!
github_username:  biplobsd # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
